[custom]


;规则集定义
ruleset=🤖 AI,https://raw.githubusercontent.com/brownff-hash/cfiles/refs/heads/main/AI.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=📲 Whatsapp,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Whatsapp.list
ruleset=📲 Whatsapp,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Whatsapp/Whatsapp.yaml
ruleset=📲 X,https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Twitter.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🍀 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🎞️ 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🐟 漏网之鱼,[]FINAL



;策略组定义
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🚀 节点选择`select`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 港台节点`[]🔯 日新节点`[]🔯 亚太节点`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]♻️ 自动选择`[]🚀 节点选择`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 港台节点`[]🔯 日新节点`[]🔯 亚太节点
custom_proxy_group=📲 Telegram`select`[]♻️ 自动选择`[]🚀 节点选择`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 港台节点`[]🔯 日新节点`[]🔯 亚太节点
custom_proxy_group=📲 Whatsapp`select`[]♻️ 自动选择`[]🚀 节点选择`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 港台节点`[]🔯 日新节点`[]🔯 亚太节点
custom_proxy_group=🍀 Google`select`[]♻️ 自动选择`[]🚀 节点选择`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 港台节点`[]🔯 日新节点`[]🔯 亚太节点
custom_proxy_group=👨🏿‍💻 GitHub`select`[]♻️ 自动选择`[]🚀 节点选择`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 港台节点`[]🔯 日新节点`[]🔯 亚太节点
custom_proxy_group=🍎 Apple`select`[]♻️ 自动选择`[]DIRECT`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 港台节点`[]🔯 日新节点`[]🔯 亚太节点
custom_proxy_group=🤖 AI`select`[]♻️ 自动选择`[]🚀 节点选择`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 日新节点
custom_proxy_group=📲 X`select`[]♻️ 自动选择`[]🚀 节点选择`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 日新节点
custom_proxy_group=🎵 TikTok`select`[]♻️ 自动选择`[]🚀 节点选择`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 港台节点`[]🔯 日新节点`[]🔯 亚太节点
custom_proxy_group=🎥 Netflix`select`[]♻️ 自动选择`[]🚀 节点选择`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 港台节点`[]🔯 日新节点`[]🔯 亚太节点
custom_proxy_group=🌍 国外媒体`select`[]♻️ 自动选择`[]🚀 节点选择`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 港台节点`[]🔯 日新节点`[]🔯 亚太节点
custom_proxy_group=🎞️ 国内媒体`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🛡️ 隐私防护`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]♻️ 自动选择`[]🚀 节点选择`[]🏡 Socks节点`[]🔯 美国节点`[]🔯 欧洲节点`[]🔯 港台节点`[]🔯 日新节点`[]🔯 亚太节点

;节点组定义
custom_proxy_group=🏡 Socks节点`url-test`(JMS|JMS)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🔯 美国节点`url-test`(美国|加拿大|美国|c60s3|c60s1|c60s2|US|CA)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🔯 欧洲节点`url-test`(英国|德国|法国|西班牙|奥地利|巴西|荷兰|瑞典|哥伦比亚|南非|以色列|瑞士|智利|英国|UK|DE|FR|ES|AT|BR|NL|SE|c60s5|CO|ZA|IL|CH|CL)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🔯 港台节点`url-test`(香港|HK|台湾|TW)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🔯 日新节点`url-test`(日本|JP|新加坡|SG|c60s4)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🔯 亚太节点`url-test`(澳大利亚|越南|马来西亚|印度|韩国|泰国|韩国|AU|MY|IN|VN|UZ)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🔯 故障转换`fallback`(?=.*(JMS|HK|TW|US|SG))^((?!(非大陆专用|海外用户)).)*$`http://www.gstatic.com/generate_204`300,,50


;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true

